### ISSUE TITLE
Don't create and save config.yml

### ISSUE THREAD

**Issue by matcracker** [LegendOfMCPE/PVPWorld#2]
[CRITICAL] Could not save Config C:\Users\Matteo\Desktop\PocketMine-MultiServer\PocketMine-MP(Lobby)\plugins\PVPWorld/config.yml: file_put_contents(C:\Users\Matteo\Desktop\PocketMine-MultiServer\PocketMine-MP(Lobby)\plugins\PVPWorld/config.yml): failed to open stream: No such file or directory

**Comment by iksaku** [comment]
This plugin is outdated
